FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY blazor23.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app/publish

FROM oracleclient:23.26 AS runtime
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "blazor23.dll"]
